** 1. zadatak (1 poen)**
<br>
Rešiti sistem jednačina
<br>
$x_1 - x_2 = 2$
<br>
$x_1 + x_2 = 4$
<br>
$2\cdot x_1 + x_2 = 8$
<br>
i dati ocenu sume kvadrata reziduala. 

In [2]:
import numpy as np

In [6]:
# Zapisujemo sistem u obliku Ax = b
A = np.array([[1, -1], [1, 1], [2, 1]])
b = np.array([[2], [4], [8]])
print(A)
print(b)
print(A.shape)
print(b.shape)

[[ 1 -1]
 [ 1  1]
 [ 2  1]]
[[2]
 [4]
 [8]]
(3, 2)
(3, 1)


In [9]:
sol = np.linalg.lstsq(A, b)
sol[0]

/usr/lib/python2.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([[3.28571429],
       [1.14285714]])

In [10]:
A.dot(sol[0])

array([[2.14285714],
       [4.42857143],
       [7.71428571]])

In [12]:
residuals = sol[1]
residuals[0]

0.2857142857142848