## Norme

** L1 norma ** matrice (maksimalni zbir apsolutnih vrednosti kolone)

$\|M\|_{1} = max_{1\leq j \leq n} \sum_{i=1}^{n}|m_{ij}|$  

In [1]:
import numpy as np
import numpy.linalg as la

In [3]:
M = np.array([[2, 3, 4], [-1, 2, 3], [4, 3, 22]])
M

array([[ 2,  3,  4],
       [-1,  2,  3],
       [ 4,  3, 22]])

### Rucno izracunavamo l1 normu matrice

In [15]:
# uzimamo abs vrednosti u matrici
Mprime = np.apply_along_axis(np.abs, axis=1, arr=M)
Mprime

array([[ 2,  3,  4],
       [ 1,  2,  3],
       [ 4,  3, 22]])

In [16]:
# Sumiramo vrste
Mprime = Mprime.sum(axis=1)
Mprime

array([ 9,  6, 29])

In [18]:
# Trazimo maxkmum
l1_norm = Mprime.max()
l1_norm

29

Naravno, isto se moze uciniti koristeci
```python
numpy.linalg``` modul

In [19]:
l1_norm = la.norm(M, ord=1)
l1_norm

29.0

## Frobenijusova norma (euklidska norma)

$\|M\|_{frob} = \sqrt{\sum_{i=1}^{n} \sum_{j=1}^{m} a_{ij}^2}$  

In [40]:
la.norm(M, ord='fro')

23.49468024894146

In [34]:
Mprime = np.apply_along_axis(lambda x: x*x, axis=1, arr=M)
Mprime

array([[  4,   9,  16],
       [  1,   4,   9],
       [ 16,   9, 484]])

In [37]:
Mprime2 = Mprime.sum(axis=0)
Mprime2

array([ 21,  22, 509])

In [38]:
Mprime3 = Mprime2.sum(axis=0)
Mprime3

552

In [39]:
np.sqrt(Mprime3)

23.49468024894146

## L2 norma

In [42]:
la.norm(M, ord=2)

23.242882345897012